# Generated by Django 3.1.4 on 2020-12-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='lng',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
