# Generated by Django 3.1.4 on 2020-12-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201215_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
        migrations.AlterField(
            model_name='user',
            name='lng',
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
    ]
