# Generated by Django 3.1.4 on 2020-12-15 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import items.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('quant', models.IntegerField(blank=True, default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('details', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=items.models.user_directory_path)),
                ('itemType', models.CharField(choices=[('Tec', 'Tecnologia'), ('Mue', 'Muebles'), ('Tbr', 'Trabajo'), ('Veh', 'Vehiculos'), ('Alm', 'Alimentos'), ('Rop', 'Ropa'), ('Sld', 'Salud'), ('Mac', 'Mascotas'), ('Hog', 'Hogar'), ('Dep', 'Deportivos'), ('Otr', 'Otros')], default='Tec', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('interest', multiselectfield.db.fields.MultiSelectField(choices=[('Tec', 'Tecnologia'), ('Mue', 'Muebles'), ('Tbr', 'Trabajo'), ('Veh', 'Vehiculos'), ('Alm', 'Alimentos'), ('Rop', 'Ropa'), ('Sld', 'Salud'), ('Mac', 'Mascotas'), ('Hog', 'Hogar'), ('Dep', 'Deportivos'), ('Otr', 'Otros')], max_length=20)),
                ('state', models.CharField(blank=True, choices=[('Nv', 'Nuevo'), ('Sn', 'Seminuevo'), ('Us', 'Usado')], default='Nv', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
